### PR TITLE
Dev 1335 date independence

### PR DESCRIPTION
**Pull request by moseshll**
DEV-1335 Make hathifiles_database Date Independent

Purpose of this branch: to make it possible to see which hathifiles have been added to `hathifiles.hf` and associated tables, and thus to enable a process to load all and only the hathifiles needed to bring the database up to date.

The added table (`hf_log`) has only two fields: filename and timestamp (`hathifile` and `time`). The new `HathifilesDatabase::Log` class handles adding new entries, and querying for existing entries by type ("full" vs "upd")

The new `HathifilesDatabase::Hathifiles` class is responsible for the difference operation between hathifiles that are on the filesystem vs the hathifiles that are in `hf_log`.

A new script `exe/full_update` is intended to run daily from our Argo Workflow and it handles loading monthly ("full") and daily ("upd") files as they appear in the filesystem.

**Monthly Delta Update**
As noted in the commit message, ISSNs were causing problems for the diff operation that is supposed to cull most or all of the redundant delete/inserts on unchanged records. Previously I had hoped to be able to have the comm/sort/diff bucket chain produce a purely hathifiles-style tab-delimited file but ultimately going from database -> hathifiles can lose information due to normalization (with ISSNs at least). So the spec for a line that can be handled has expanded to allow 0/1 in addition to "allow"/"deny" in the rights column (see the `ALLOW` lambda in `linespec.rb`). And other parts of that code (Dumper) don't insist on translating these values from "database" to "hathifiles" dialect.

**Other Updates**
In addition to some TIDY commits, there are three GitHub issues and a Dependabot:

  - #11 to use healthchecks in the docker-compose file
  - #8 to use push_metrics in the new `full_update` script
  - #9 README fixes
  - Dependabot Rexml security update

**Testing**
- Please test under Docker using the test procedure noted in README.md
- Please scan `exe/full_update` for errors, omissions, or DRY violations.
- Please scan the new `Hathifiles` and `Log` classes for errors, omissions, DRY violations, and bad naming choices since they are new classes. In particular, I am not fond of the `missing_*` names in `Hathifiles`.

@niquerio I have inspected MLibrary repos that use this and I don't think there's anything here that glaringly could cause problems, except that this update has a baked-in assumption that the `hf_log` table is going to be present in the database. Is this a problem? Should this code try to accommodate the absence of `hf_log` without blowing up?

### CODE REVIEW

**Comment by niquerio** [comment]
I think it's fine to assume the table will be there. I'm assuming that my instance of the Hathifiles DB would break only if I updated the code to use this update and then didn't do an update to the tables. I'm OK with rebuilding the DB when I incorporate this update.

**Review by mwarin — APPROVED** [review]
## Please test under Docker using the test procedure noted in README.md

The command:
`docker compose run --rm test bin/setup`
... outputs an unnecessary string at the end:
"# Do any other automated setup that you need to do here"

All other build and test commands behave well.

## Please scan exe/full_update for errors, omissions, or DRY violations.

It looks like you are assuming some ENV variables exist.
I like to see some checks for those, so the code crashes more elegantly when they are missing.
E.g. `connection = HathifilesDatabase.new(ENV["HATHIFILES_MYSQL_CONNECTION"])`

`batch_size: 10_000` could be set in ENV.

Logic-wise, my only question is this:

This class loads all missing "full" files first, then all missing "update" files.
Is there any risk related to not loading them in order?

## Please scan the new Hathifiles and Log classes

... for errors, omissions, DRY violations, and bad naming choices since they are new classes.
In particular, I am not fond of the missing_* names in Hathifiles

### hathifiles.rb

A brief comment at the top of `hathifiles.rb` wouldn't hurt.

The line:
```
max = Dir.glob(File.join(hathifiles_directory, "hathi_full*")).max
```
... might produce unwanted results if there are any manipulated files in the dir.
E.g. `hathi_full_20240101.tsv~`. A tighter glob might proof against that.

In `update_hathifiles` I think it would be prudent to put anchor(s) in the regex:
`hathifile.match(/hathi_upd_(\d{8}$)/`
or
`hathifile.match(/^hathi_upd_(\d{8}$)/`
... depending on if they are full paths or basenames. Again, just to tighten up the glob.

`update_hathifiles` itself pushes the limit for how long of an exression I like to read.
Takes a while to parse, as a human. I wouldn't mind if you broke it down into parts,
even though that messes with the neat memoization. You could essentially re-use the general
shape from `missing_update_hathifiles` to improve readability.

`latest_full_hathifile_date`: again, consider anchors (^ and/or $) in regex.

### log.rb

I note the comment on top with a nod of approval.

The form `def initialize(connection:)` was new to me (yay learning!).
Is there any point in using this form for functions that only take a single arg?

Any downsides to declaring log_table in the constructor and do away with the whole `private` block?

`all_of_type` uses a `LIKE %x%` query. That surprised me, but maybe that makes sense.
A comment saying:
`# expected column values look like "x" or "y"`
might temper my surprise.
Would `LIKE "hathi_#{type}%"` work? Very nitpicky, I know.


## Misc

### README

I love the attention to detail in the README. Nice.

There are things mentioned as `_deprecated_`. Is there a plan for these?

### tests

It took me a while to see what the difference in these tests were, such that one evals true and the other false:
```
describe "#exist?" do
  it "returns `true` if log entry exists" do
    log.add(hathifile: "hathi_full_20231231.txt.gz")
    expect(log.exist?(hathifile: "hathi_full_20231231.txt.gz")).to eq true
  end

  it "returns `false` if log entry does not exist" do
    log.add(hathifile: "hathi_full_20231231.txt.gz")
    expect(log.exist?(hathifile: "hathi_full_20241231.txt.gz")).to eq false
  end
end
```

**Comment by moseshll** [comment]
@mwarin thanks for all the helpful commentary. I think the comments helped with readability, especially after rethinking how to make the filename regexes stricter but more readable. Some code desiccation happened as well. And it was a relief getting real regex constants, and not doing all the heavy lifting with globs (which I really have never liked).

To address a couple of the questions raised:
- I favor using Hash params everywhere, even when there's only one param and it's absurdly redundant (`process_the_thing(thing: thing)` _ugh_) because parameters never go away, more get added. And a single parameter may not be memorable or obvious (e.g. a Boolean). So why make a judgment call every time you write a one-param method? (I think I talked myself into my own soapbox now.)
- Since this is a (admittedly unpublished and bizarre) gem, and MLibrary use it, I'm hesitant to just chuck out deprecated stuff without a lot of advance warning. I figure the chucking-out party can kick off a couple minor versions in the future.

**Comment by mwarin** [comment]
Neat! It was already approved, now it is *emphatically* approved.

**Pull request merged**
